system:
  env: public
  addr: 8000

zap:
  level: info
  format: console
  prefix: '[紫讯科技]'
  director: log
  link-name: latest_log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace



dingtalk:
  agentId: 1515778455
  appKey: dingkaxiw6y35djuy1cb
  appSecret: ZA4vTnGK7wy1hZDuZ-oG3IvC9ZaymOCCswbMeCe6V0guaeigq1aXDA91FIhyBr5J