system:
  env: public
  addr: 8888

zap:
  level: info
  format: console
  prefix: '[紫讯科技]'
  director: log
  link-name: latest_log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace

